<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /Users/monish/src/civi-extensions/biz.jmaconsulting.aogolfevent/xml/schema/CRM/Aogolfevent/EventContributionPF.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:89d9f9dbc833cfda4bd1ac7ef8a4e622)
 */

/**
 * Database access object for the EventContributionPF entity.
 */
class CRM_Aogolfevent_DAO_EventContributionPF extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_event_contribution_pf';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique EventContributionPF ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Price Field
   *
   * @var int
   */
  public $price_field_id;

  /**
   * @var bool
   */
  public $is_donation;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_event_contribution_pf';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'price_field_id', 'civicrm_price_field', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Unique EventContributionPF ID'),
          'required' => TRUE,
          'where' => 'civicrm_event_contribution_pf.id',
          'table_name' => 'civicrm_event_contribution_pf',
          'entity' => 'EventContributionPF',
          'bao' => 'CRM_Aogolfevent_DAO_EventContributionPF',
          'localizable' => 0,
        ],
        'price_field_id' => [
          'name' => 'price_field_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('FK to Price Field'),
          'where' => 'civicrm_event_contribution_pf.price_field_id',
          'table_name' => 'civicrm_event_contribution_pf',
          'entity' => 'EventContributionPF',
          'bao' => 'CRM_Aogolfevent_DAO_EventContributionPF',
          'localizable' => 0,
        ],
        'is_donation' => [
          'name' => 'is_donation',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Is used for Donation'),
          'import' => TRUE,
          'where' => 'civicrm_event_contribution_pf.is_donation',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_event_contribution_pf',
          'entity' => 'EventContributionPF',
          'bao' => 'CRM_Aogolfevent_DAO_EventContributionPF',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'event_contribution_pf', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'event_contribution_pf', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
